version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: weather-app-frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    environment:
      - BACKEND_URL = "localhost:5000/api/v1"
    networks:
      - cowlar-weather-app

  backend:
    build: ./backend
    container_name: weather-app-backend
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - influxdb
    environment:
      - MONGODB_URL=mongodb+srv://hureracowlar:hurera.cowlar.141@cluster0.lfzt6va.mongodb.net/weatherapp?retryWrites=true&w=majority
      - BACKEND_PORT=5000
      - JWT_SECRET=cowsarecool
      - JWT_EXPIRES_IN=10m
      - MQTT_BROKER_HOST=e586d81940394ed89ccc8493d8b32568.s1.eu.hivemq.cloud
      - MQTT_BROKER_PORT=8883
      - MQTT_CLIENT_USERNAME=hivemq.webclient.1707853998095
      - MQTT_CLIENT_PASSWORD=E4*lx<0?N8tQ>dF7HBmb
      - MQTT_TOPIC=weather/#
      - INFLUXDB_HOST=http://influxdb:8086
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - INFLUXDB_ORG=weather-org
      - INFLUXDB_BUCKET=weather-bucket
    networks:
      - cowlar-weather-app

  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - ./influxdata:/var/lib/influxdb2
      - ./config:/etc/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=weather-org
      - DOCKER_INFLUXDB_INIT_BUCKET=weather-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    networks:
      - cowlar-weather-app

networks:
  cowlar-weather-app:
    driver: bridge
